### ISSUE TITLE
Setting Visibility="Collapsed" crashes ColorControl

### ISSUE THREAD

**Issue by BrianLima** [zubetto/ColorControl#3]
Just setting the whole control visibility to Collapsed instead of Hidden crashes any app using it.

**Comment by zubetto** [comment]
Um ... I tried to hide and collapse the entire ColorControl (and the alpha slider) during the test program and everything worked fine. What kind of exception it throws in your case?

**Comment by BrianLima** [comment]
It crashes if I leave it collapsed on the XAML, so the form loads with the control already collapsed, it crashes with a null reference exception.

**Comment by zubetto** [comment]
Think I fixed this and also the accidentally detected problem with sliders (commit: _Slider clicks fixed ; Visibility.Collapsed fixed_)

**Comment by BrianLima** [comment]
It is still crashing if colorcontrol is initially collapsed, it tries to find theThumb but as it is collapsed it returns null and the code can't continue

`            // Green
            theThumb = sliderGreen.Template.FindName("TrackThumb", sliderGreen) as Thumb;
            theEllipse = theThumb.Template.FindName("Ellipse", theThumb) as Ellipse;
            thumbGbrush = theEllipse.Fill as SolidColorBrush;
`

Maybe detect if theThumb or theEllipse is null and don't continue IniThumbsBrushes()?

**Comment by zubetto** [comment]
Hope now it will work properly ))
I just absolutely forgot about the TemplateBinding and instead of using the _Foreground_ property bound to the Ellipse.Fill, I created this terrible method. Those _Template.FindName()_ were headache for me!
